SERIES_SPECS = {
    "fred:WALCL": {
        "belief": "central_bank_liquidity",
        "direction": 1,
        "weight": 0.45,
        "feature": "change_4",
        "scale": 100000.0,
        "correlation_group": "fed_balance_sheet",
        "max_freshness_days": 10,
        "description": "Federal Reserve total assets",
    },
    "fred:RESPPLLOPNWW": {
        "belief": "central_bank_liquidity",
        "direction": 1,
        "weight": 0.30,
        "feature": "change_4",
        "scale": 50000.0,
        "correlation_group": "bank_reserves",
        "max_freshness_days": 10,
        "description": "Reserve balances",
    },
    "fred:WTREGEN": {
        "belief": "treasury_liquidity",
        "direction": -1,
        "weight": 0.55,
        "feature": "change_4",
        "scale": 100000.0,
        "correlation_group": "treasury_cash",
        "max_freshness_days": 10,
        "description": "Treasury General Account",
    },
    "fred:RRPONTSYD": {
        "belief": "money_market_liquidity",
        "direction": -1,
        "weight": 0.55,
        "feature": "change_4",
        "scale": 100.0,
        "correlation_group": "reverse_repo",
        "max_freshness_days": 3,
        "description": "Overnight reverse repo usage",
    },
    "fred:SOFR": {
        "belief": "money_market_stress",
        "direction": 1,
        "weight": 0.50,
        "feature": "z_score",
        "scale": 2.0,
        "correlation_group": "secured_funding",
        "max_freshness_days": 3,
        "description": "Secured overnight funding rate",
    },
    "fred:DFF": {
        "belief": "policy_restrictiveness",
        "direction": 1,
        "weight": 0.35,
        "feature": "level",
        "scale": 5.0,
        "correlation_group": "policy_rates",
        "max_freshness_days": 3,
        "description": "Effective federal funds rate",
    },
    "fred:DGS2": {
        "belief": "front_end_restrictiveness",
        "direction": 1,
        "weight": 0.50,
        "feature": "z_score",
        "scale": 2.0,
        "correlation_group": "nominal_rates",
        "max_freshness_days": 3,
        "description": "Two-year Treasury yield",
    },
    "fred:DGS10": {
        "belief": "long_rate_pressure",
        "direction": 1,
        "weight": 0.45,
        "feature": "z_score",
        "scale": 2.0,
        "correlation_group": "nominal_rates",
        "max_freshness_days": 3,
        "description": "Ten-year Treasury yield",
    },
    "fred:DFII10": {
        "belief": "real_yield_pressure",
        "direction": 1,
        "weight": 0.70,
        "feature": "z_score",
        "scale": 2.0,
        "correlation_group": "real_rates",
        "max_freshness_days": 3,
        "description": "Ten-year real yield",
    },
}

COMPONENT_WEIGHTS = {
    "central_bank_liquidity": 0.40,
    "treasury_liquidity": 0.30,
    "money_market_liquidity": 0.30,
}

RATE_WEIGHTS = {
    "policy_restrictiveness": 0.20,
    "front_end_restrictiveness": 0.25,
    "long_rate_pressure": 0.20,
    "real_yield_pressure": 0.35,
}
