
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS beliefs (belief_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), belief_key TEXT NOT NULL, probability DOUBLE PRECISION NOT NULL, confidence DOUBLE PRECISION, evidence JSONB NOT NULL DEFAULT '[]', model_version TEXT NOT NULL DEFAULT '3.50', updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_beliefs_key_time ON beliefs(belief_key,updated_at DESC);
CREATE TABLE IF NOT EXISTS regimes (regime_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), regime_key TEXT NOT NULL, probability DOUBLE PRECISION NOT NULL, evidence JSONB NOT NULL DEFAULT '[]', model_version TEXT NOT NULL DEFAULT '3.50', as_of TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS jobs (job_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), queue TEXT NOT NULL, job_type TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'queued', priority INTEGER NOT NULL DEFAULT 100, attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 5, run_after TIMESTAMPTZ NOT NULL DEFAULT NOW(), locked_at TIMESTAMPTZ, locked_by TEXT, last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_jobs_claim ON jobs(queue,status,priority,run_after) WHERE status='queued';
CREATE TABLE IF NOT EXISTS publications (publication_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), publication_type TEXT NOT NULL, subject TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'rendered', trace_id UUID DEFAULT gen_random_uuid(), model_version TEXT NOT NULL DEFAULT '3.50', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS gmail_delivery_records (gmail_delivery_record_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), publication_id UUID REFERENCES publications(publication_id), recipient_email TEXT NOT NULL, delivery_mode TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, status TEXT NOT NULL, draft_id TEXT, message_id TEXT, thread_id TEXT, error_message TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS approval_packages (approval_package_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), candidate_version TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', metrics JSONB NOT NULL DEFAULT '{}', approved_by TEXT, approved_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
